name: Experimental Rubies CI Run
on:
  schedule:
    - cron:  '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        ruby: [head, jruby-head, truffleruby-head]

    env:
      JAVA_OPTS: '-Xmx1024m'
      RUBYOPT: '-w'
      JRUBY_OPTS: '--dev'

    name: "Tests: Experimental Ruby ${{ matrix.ruby }}"
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake ci
