name: Experimental Rubies CI Run
on:
  schedule:
    - cron:  '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        ruby: [head, truffleruby, truffleruby-head]

    env:
      JAVA_OPTS: '-Xmx1024m'
      RUBYOPT: '-w'
      JRUBY_OPTS: '--dev'

    name: "Tests: Experimental Ruby ${{ matrix.ruby }}"
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: Setup system Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: |
        echo JAVA_OPTS: $JAVA_OPTS
        bundle exec rake ci
